language: node_js
node_js:
  - "lts/dubnium"
cache: yarn

install:
  - yarn install --frozen-lockfile

script:
  - node ./tools/licenses/fetchLicenses.js
  - yarn lint
  - yarn test

# Only build on pushes or PRs to these branches
branches:
  only:
  - master
  - develop
